language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master
  
install:
  - npm install -g vsce

script:
  - echo "Publish VSCode package..."
  - vsce publish -p $PUBLISHER_KEY